[package]
name = "vish"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.155"
sqlite = "0.36.0"
termios = "0.3.3"

[build-dependencies]
cc = "1.0.97"
